# Generated by Django 2.2.1 on 2019-11-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('sell_USD', models.FloatField()),
                ('buy_USD', models.FloatField()),
            ],
        ),
    ]
